#!/usr/bin/env bash
alias asdf="setxkbmap us real-prog-dvorak"
alias aoeu="setxkbmap us"
alias lkj="setxkbmap us real-prog-dvorak"
alias snth="setxkbmap us"
alias xsc="xclip -selection clipboard"

#!/usr/bin/env bash
alias vim="$VIM"
alias work="cd ~/work"

alias python="python3"
alias ebc="$VIM $DOTFILES/zsh/.zshrc"
alias ebp="$VIM $DOTFILES/zsh/.zsh_profile"
alias etc="$VIM $DOTFILES/tmux/.tmux.conf"
alias enrc="nvim $DOTFILES/nvim/.config/nvim/init.vim"
alias eirc="nvim $XDG_CONFIG_HOME/i3/i3config"
alias bp="dotFileInstall && source ~/.zshrc"
alias dotFileInstall="$DOTFILES/install"

alias cclip="xclip -selection clipboard"
alias pclip="xclip -selection clipboard"
